name: Build macOS Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pyinstaller
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile main.py

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: macos-executable
          path: dist/main
